import { loadLocalEnv } from './load-env'

loadLocalEnv()

export const config = {
  url: process.env.VITE_BACKEND_URL || '',
  timeout: Number(process.env.VITE_TIMEOUT || 90000),
  vertexProjectId: process.env.VERTEX_PROJECT_ID || '',
  vertexLocation: process.env.VERTEX_LOCATION || 'asia-northeast3',
  vertexApiEndpoint: process.env.VERTEX_API_ENDPOINT || '',
  vertexAccessToken: process.env.VERTEX_ACCESS_TOKEN || '',
  milvusAddress: process.env.MILVUS_ADDRESS || 'milvus:19530',
  milvusToken: process.env.MILVUS_TOKEN || '',
  milvusDatabase: process.env.MILVUS_DATABASE || 'default',
  milvusCollection: process.env.MILVUS_COLLECTION || 'pagelm_chunks',
  archiveSnapshotFile: process.env.ARCHIVE_SNAPSHOT_FILE || '',
  litellmBaseUrl: process.env.LITELLM_BASE_URL || 'https://proxy.qai.lge.com/v1',
  litellmApiKey: process.env.LITELLM_API_KEY || '',
  litellmDefaultModelAlias: process.env.LITELLM_DEFAULT_MODEL_ALIAS || 'pagelm-default',
  litellmAllowedModelAliases: [...new Set((process.env.LITELLM_ALLOWED_MODEL_ALIASES || 'pagelm-default')
    .split(',').map(value => value.trim()).filter(Boolean))],
  openai: process.env.OPENAI_API_KEY || '',
  temp: Number(process.env.LLM_TEMP || 1),
  max_tokens: Number(process.env.LLM_MAXTOK || 16384),
  port: Number(process.env.PORT || 5000),
  baseUrl: process.env.VITE_BACKEND_URL || 'http://localhost:5000',
  frontendUrl: process.env.VITE_FRONTEND_URL || 'http://localhost:5173',
  tts_provider: process.env.TTS_PROVIDER || 'edge',
  ffmpeg: process.env.FFMPEG_PATH || 'ffmpeg',
  tts_voice_edge: process.env.TTS_VOICE_EDGE || 'en-US-AvaNeural',
  tts_voice_alt_edge: process.env.TTS_VOICE_ALT_EDGE || 'en-US-AndrewNeural',
  eleven_api_key: process.env.ELEVEN_API_KEY || '',
  eleven_voice_a: process.env.ELEVEN_VOICE_A || '',
  eleven_voice_b: process.env.ELEVEN_VOICE_B || '',
  google_creds: process.env.GOOGLE_APPLICATION_CREDENTIALS || '',
  tts_voice_google: process.env.TTS_VOICE_GOOGLE || 'en-US-Neural2-F',
  tts_voice_alt_google: process.env.TTS_VOICE_ALT_GOOGLE || 'en-US-Neural2-D',
  speech_sdk_model: process.env.SPEECH_SDK_MODEL || 'openai/gpt-4o-mini-tts',
  speech_sdk_voice_a: process.env.SPEECH_SDK_VOICE_A || 'alloy',
  speech_sdk_voice_b: process.env.SPEECH_SDK_VOICE_B || 'echo',
  transcription_provider: process.env.TRANSCRIPTION_PROVIDER || 'openai',
  assemblyai_api_key: process.env.ASSEMBLYAI_API_KEY || '',
  google_project_id: process.env.GOOGLE_CLOUD_PROJECT_ID || '',
}
